import { Expenses, FullVehicles } from "../interfaces/interfaces";

export const GlobalContextConfigDeclarations = {
    authorization: false,
    currentUser: "",
    currentTotalPages: [],
    filterOption: "",
    fullVehicles: [],
    ITEMS_PER_PAGE: 10,
    lastUpdateKilometer: 0,
    newAlert: { nombreAlerta: "", kilometros: "" },
    page: 1,
    rubros:[],
    sorted: "",
    toogleFilter2: false,
    selectedVehicles: [],
    updateCars: false,
    filterExpenseByDate: (date1: Date, date2: Date, subFiltro: boolean) => "",
    handleAdd: (vehicle:FullVehicles)=>"",
    handleAlert: (e: React.ChangeEvent<HTMLSelectElement> | React.ChangeEvent<HTMLInputElement>) => "",
    handleAuth: (user: string) => "",
    handleInput: (e: React.ChangeEvent<HTMLInputElement>) => "",
    handleChange: (e: React.ChangeEvent<HTMLInputElement>, vehicle: FullVehicles) => "",
    handlePageChange: (pageNumber: number) => "",
    handlePriceFilter: (e: React.ChangeEvent<HTMLInputElement>) => "",
    handleRemove: (vehicle:FullVehicles)=>"",
    handleResetFilter: (value: string) => "",
    handleSearch:(vehicle:FullVehicles)=>false,
    handleSelectedVehicles: () => "",
    handleSetSelected: (newAlert: Object) => "",
    handleSetCurrentTotalPages: (arr: Expenses[]) => "",
    handleSetFilter: (e: React.ChangeEvent<HTMLSelectElement>) => "",
    handleSET_ITEM_PER_PAGE: (e: React.ChangeEvent<HTMLSelectElement>) => "",
    handleSorted: (value: string) => "",
    handleToogleFilter2: () => "",
    handleUpdateKilometer: (e: React.ChangeEvent<HTMLInputElement> | number) => "",
    handleUpdateCars: () => "",
    navigate: () => "",
    saveVehicle: (vehicle: any) => "",
    removeVehicle: (coleccion: string, id: string) => "",
    resetExpenses: () => "",
    resetAlert: () => "",
    sortFullExpenses: (expenses: Expenses[], option: string) => {},
  }